### ISSUE TITLE
a question of code

### ISSUE THREAD

**Issue by Bri1987** [RayZhhh/funsearch#2]
Thank you for your great work! But I noticed that in the LocalLLM class of the "funsearch_bin_packing_local_llm.py" file, the _additional_prompt is initialized in the __init__ method. However, it seems that it is not passed to the LLM-server through the data. Is it a bug or I don't understand your work entirely ?

**Comment by RayZhhh** [comment]
Hi😄! Thank you for your report !!! The FunSearch pipeline does not need the '_additional_prompt'. More accurately, FunSearch is designed to work with ''code completion style models'' (e.g., StarCoder, CodeLlama, ...), for which additional prompts and instructions are not really required. For other "instruct-based models" such as DeepSeek-coder, LLama, GPT-3.5..., it is not sure if adding a prompt based on the original prompt can help better/quicker convergence. You may test it !!! 😁

**Comment by Bri1987** [comment]
ok, thanks you a lot !
