### ISSUE TITLE
How long was the overall run?

### ISSUE THREAD

**Issue by Drkiller-ui** [RayZhhh/funsearch#3]
How long was the overall run?
 It ran for 1h and the score didn't change. 
Thank you.

**Comment by RayZhhh** [comment]
Hi! Thank you for your report. Could you please provide more details? 

1. Which file did you run and could you please demonstrate your code/output logs here? If you were using LLM API, please check if the API key is set correctly. 

2. How many samples did you get in an hour? What LLM did you use?

3. You may terminate the search process by setting the `global_max_sample_num = 10` to funsearch.main(). If this parameter is `None`, the search process will run an endless loop.

**Comment by Drkiller-ui** [comment]
@RayZhhh 
```
INFO:absl:Best score of island 0 increased to -500.0
INFO:absl:Best score of island 1 increased to -500.0
INFO:absl:Best score of island 2 increased to -500.0
INFO:absl:Best score of island 3 increased to -500.0
INFO:absl:Best score of island 4 increased to -500.0
INFO:absl:Best score of island 5 increased to -500.0
INFO:absl:Best score of island 6 increased to -500.0
INFO:absl:Best score of island 7 increased to -500.0
INFO:absl:Best score of island 8 increased to -500.0
INFO:absl:Best score of island 9 increased to -500.0
================= Evaluated Function =================
def priority(item: float, bins: np.ndarray) -> np.ndarray:
    """Returns priority with which we want to add item to each bin.

    Args:
        item: Size of item to be added to the bin.
        bins: Array of capacities for each bin.

    Return:
        Array of same size as bins with priority score of each bin.
    """
    ratios = item / bins
    log_ratios = np.log(ratios)
    priorities = -log_ratios
    return priorities
------------------------------------------------------
Score        : -500.0
Sample time  : None
Evaluate time: 2.635921001434326
Sample orders: None
======================================================
```
It stays parked without any change, I tested the api and there is no problem.
  `global_max_sample_num = 10` has been set

**Comment by Drkiller-ui** [comment]
@RayZhhh 
I have solved it,  changing from `api.chatanywhere.com.cn` to `api.chatanywhere.tech`. 
Thanks for your excellent project.
